apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: employee-pvc
  namespace: dev

spec:
  storageClassName: ""

  volumeName: employee-pv

  accessModes:
  - ReadWriteOnce

  resources:
    requests:
      storage: 500Mi
